[package]
name = "hyperlolog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2.11"
siphasher = "1.0.0"
thiserror = "1.0.50"

